version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./data/mysqldb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django

  django:
    image: django
    command: python ./usr/src/app/mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/app:/usr/src/app
    links:
      - db
    ports:
      - "8000:8000"
