# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20170830_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
