# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_host_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(blank=True, max_length=20)),
                ('db_name', models.CharField(blank=True, max_length=30)),
                ('db_version', models.CharField(blank=True, max_length=20)),
                ('db_session', models.IntegerField()),
                ('db_lock', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='application',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='host',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='host',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='host',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='system',
        ),
        migrations.RemoveField(
            model_name='oracle',
            name='db_id',
        ),
        migrations.RemoveField(
            model_name='oracle',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='oracle',
            name='db_version',
        ),
        migrations.AddField(
            model_name='hostmetric',
            name='application',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostmetric',
            name='cpu',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='hostmetric',
            name='disk',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='hostmetric',
            name='hostname',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='hostmetric',
            name='memory',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='hostmetric',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hostmetric',
            name='system',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='oraclemetric',
            name='oracle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Oracle'),
        ),
    ]
